FROM node:21.7.3-alpine

WORKDIR /app

# Copy package.json and package-lock.json before other files to leverage Docker cache
COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ENV DATABASE_URL=
ENV NEXT_PUBLIC_GA_ID=
ENV NEXT_PUBLIC_DEV_MODE=
ENV NEXT_TELEMETRY_DISABLED=
ENV KINDE_CLIENT_ID=
ENV KINDE_CLIENT_SECRET=
ENV KINDE_ISSUER_URL=
ENV KINDE_SITE_URL=
ENV KINDE_POST_LOGOUT_REDIRECT_URL=
ENV KINDE_POST_LOGIN_REDIRECT_URL=
ENV NEXT_PUBLIC_KINDE_CONNECTION_EMAIL_PASSWORD=
ENV NEXT_PUBLIC_KINDE_CONNECTION_GOOGLE=
ENV NEXT_PUBLIC_KINDE_CONNECTION_GITHUB=
ENV OPENAI_API_KEY=

RUN npx prisma generate

CMD ["sh", "-c", "npm run build && npm start"]