name: Build, Deploy to GHCR and Change Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-docker-build:
    uses: Jannik-Schroeder/workflows/.github/workflows/docker-build-node.yaml@main
    permissions:
      contents: write
      packages: write
      id-token: write

  change-version:
    needs: call-docker-build
    uses: Jannik-Schroeder/workflows/.github/workflows/update-kubernetes-version.yaml@main
    secrets:
      PRIVATE_REPO_KEY: ${{ secrets.PRIVATE_REPO_KEY }}
    permissions:
      contents: write
    with:
      repository: DanielWTE/wglc-kubernetes
      branch: main
      file: ./services/educdia-app.yaml
      version: ${{ needs.call-docker-build.outputs.version }}
      image: danielwte/educdia-app
      username: DanielWTE
